 Shadowrocket: 2026-04-12 23:46:39
[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://8.8.8.8/dns-query, https://1.1.1.1/dns-query, https://94.140.14.14/dns-query
fallback-dns-server = https://8.8.4.4/dns-query, https://1.0.0.1/dns-query
hijack-dns = *:53
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
icmp-auto-reply = true
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/devel6373/Proxy_for_tg/refs/heads/main/Shadowrocket.conf

[Proxy Group]
AUTO = fallback,XANKAVPN.XYZ,ACCOUNT.GEODEMA.ORG,use=true,policy-select-name=🇵🇱 ПОЛЬША 2 [XANKAVPN],interval=300,timeout=5,url=http://cp.cloudflare.com/generate_204,policy-regex-filter=^(?!.*(Россия|🇷🇺|Russia|RU-)).*

[Rule]
# Блокировка рекламы
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising.list,REJECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising_Domain.list,REJECT
# Блокировка трекеров
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Privacy/Privacy.list,REJECT
#Свои домены
DOMAIN-SUFFIX,cdn.prod.website-files.com,AUTO
DOMAIN-SUFFIX,infoapi24.store,AUTO
DOMAIN-SUFFIX,promptcowboy.ai,AUTO
# Маршрутизация
RULE-SET,https://raw.githubusercontent.com/Moli-X/Resources/fdbde405cdbb6f52f4e5661ffff8426fa321a211/Ruleset/AI.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Facebook/Facebook.list,AUTO
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/refs/heads/main/rules/voice_ports.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Telegram/Telegram.list,AUTO
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/refs/heads/main/rules/domains_community.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Google/Google.list,AUTO
# Финал
GEOIP,RU,DIRECT
FINAL,DIRECT
